#index:
#    path: /
#    controller: App\Controller\DefaultController::index

inicio:
    path: /inicio
    controller: App\Controller\HomeController::index
    
imagen:
    path: /imagen
    controller: App\Controller\ImagenController::index
    
imagen_save:
    path: /imagen/save
    controller: App\Controller\ImagenController::save
    methods: [POST]

imagen_detail:
    path: /imagen/{id}
    controller: App\Controller\ImagenController::imagen

imagen_update:
    path: /imagen/update/{id}
    controller: App\Controller\ImagenController::update

imagen_delete:
    path: /imagen/delete/{id}
    controller: App\Controller\ImagenController::delete

crear_imagen:
    path: /crear-imagen
    controller: App\Controller\ImagenController::createImagen

    
