#index:
#    path: /
#    controller: App\Controller\DefaultController::index

inicio:
    path: /inicio
    controller: App\Controller\HomeController::index
    
imagenes:
    path: /imagenes
    controller: App\Controller\HomeController::imagenes  
    
