#index:
#    path: /
#    controller: App\Controller\DefaultController::index

inicio:
    path: /inicio
    controller: App\Controller\HomeController::index
    
imagen:
    path: /imagen
    controller: App\Controller\ImagenController::index
    
imagen_save:
    path: /imagen/save
    controller: App\Controller\ImagenController::save
    
